---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo-prod
  namespace: prod
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.4
spec:
  releaseName: podinfo-prod
  chart:
    git: ssh://git@github.com/delhage/gitops-helm.git
    path: charts/podinfo
    ref: master
  values:
    image: nexus.hh.atg.se:17000/lasse/podinfo:0.4.12
    replicaCount: 3
