---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo-prod
  namespace: prod
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.4
spec:
  releaseName: podinfo-prod
  chart:
    git: git@github.com:delhage/gitops-helm
    path: charts/podinfo
    ref: master
  values:
    image: nexus.hh.atg.se:17000/releases/podinfo:0.4.11
    replicaCount: 3
