{{- $appName := .Release.Name -}}
apiVersion: v1
data:
  SPRING_CLOUD_VAULT_ENABLED: 'false'
  VAULT_HOST: vault-vault.ocplab.hh.atg.se
  VAULT_PORT: "8200"
kind: ConfigMap
metadata:
  name: common-services-skeleton
  namespace: test1-common-services-skeleton
  labels:
    app: {{ $appName }}
    chart: {{ template "atg-springboot.chart" . }}
