{{- if .Values.route.enabled -}}
{{- $appName := .Release.Name -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
{{- with .Values.route.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ $appName }}
    atg-version: {{ .Values.ATGversion }}
    route: {{ .Values.route.router }}
    chart: {{ template "atg-springboot.chart" . }}
  name: {{ $appName }}
spec:
  host: {{ $appName }}-{{ .Release.Namespace }}.{{ .Values.route.domainname }}.atg.se
  port:
    targetPort: {{ .Values.route.targetport}}
  tls:
    termination: {{ .Values.route.tlstermination }}
  to:
    kind: Service
    name: {{ $appName }}
    weight: 100
  wildcardPolicy: None
{{- end }}
